# Web Server config
server:
  port: 8080

# Springdoc config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  version: 1.0

# DataSource configuration
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/ficr
    username: postgres
    password: postgres
  jackson:
    date-format: dd/MM/yyyy

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled: ALWAYS
